[package]
name = "lispers"
version = "0.1.0"
authors = ["Tim Deeb-Swihart <tim@deebswih.art>"]
edition = "2018"

[dependencies]
snafu = "0.6.10"
anyhow = "1.0.38"
log = "0.4.14"
env_logger = "0.9.0"


[[bin]]
name = "lispers"
